import { Product, TimeSlot, BrandInfo } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    nameAr: 'مياه نوفا',
    nameEn: 'Nova Water',
    price: 18.50,
    imageUrl: 'https://cdn.salla.sa/AEdwj/890c20da-085a-464a-932d-20e363539958-500x500.png',
    brand: 'Nova',
    brandId: 'nova',
    packagingType: 'CRT',
    unitVolume: '330ml',
    unitsPerPackage: 40,
    size: '330ml x 40',
    isSubscriptionAvailable: true,
    sodiumLevel: 17,
    phLevel: 7.4,
    rating: 4.8,
    reviews: 1240,
  },
  {
    id: '1-2',
    nameAr: 'مياه نوفا',
    nameEn: 'Nova Water',
    price: 19.50,
    imageUrl: 'https://cdn.salla.sa/AEdwj/890c20da-085a-464a-932d-20e363539958-500x500.png',
    brand: 'Nova',
    brandId: 'nova',
    packagingType: 'CRT',
    unitVolume: '200ml',
    unitsPerPackage: 48,
    size: '200ml x 48',
    isSubscriptionAvailable: true,
    sodiumLevel: 17,
    phLevel: 7.4,
    rating: 4.8,
    reviews: 1240,
  },
  {
    id: '2',
    nameAr: 'مياه بيرين',
    nameEn: 'Berain Water',
    price: 21.00,
    imageUrl: 'https://cdn.salla.sa/AEdwj/a9030623-f222-4467-8549-d37533604313-500x500.png',
    brand: 'Berain',
    brandId: 'berain',
    packagingType: 'CRT',
    unitVolume: '330ml',
    unitsPerPackage: 40,
    size: '330ml x 40',
    isSubscriptionAvailable: true,
    sodiumLevel: 12,
    phLevel: 7.2,
    rating: 4.7,
    reviews: 950,
  },
  {
    id: '3',
    nameAr: 'مياه تانيا',
    nameEn: 'Tania Water',
    price: 15.00,
    imageUrl: 'https://picsum.photos/200/300?random=3',
    brand: 'Tania',
    brandId: 'tania',
    packagingType: 'CRT',
    unitVolume: '200ml',
    unitsPerPackage: 48,
    size: '200ml x 48',
    isSubscriptionAvailable: false,
    sodiumLevel: 20,
    phLevel: 7.0,
    rating: 4.2,
    reviews: 340,
  },
  {
    id: '4',
    nameAr: 'مياه زمزم',
    nameEn: 'Zamzam Water',
    price: 35.00,
    imageUrl: 'https://picsum.photos/200/300?random=4',
    brand: 'Zamzam',
    brandId: 'zamzam',
    packagingType: 'PCS',
    unitVolume: '5L',
    unitsPerPackage: 1,
    size: '5L x 1',
    isSubscriptionAvailable: false,
    sodiumLevel: 40,
    phLevel: 8.0,
    rating: 5.0,
    reviews: 2500,
  },
  {
    id: '5',
    nameAr: 'مياه أروى',
    nameEn: 'Arwa Water',
    price: 19.50,
    imageUrl: 'https://picsum.photos/200/300?random=5',
    brand: 'Arwa',
    brandId: 'arwa',
    packagingType: 'CRT',
    unitVolume: '330ml',
    unitsPerPackage: 40,
    size: '330ml x 40',
    isSubscriptionAvailable: true,
    sodiumLevel: 3,
    phLevel: 6.9,
    rating: 4.5,
    reviews: 560,
  },
  {
    id: '6',
    nameAr: 'مياه أكوافينا',
    nameEn: 'Aquafina',
    price: 16.00,
    imageUrl: 'https://picsum.photos/200/300?random=6',
    brand: 'Aquafina',
    brandId: 'aquafina',
    packagingType: 'CRT',
    unitVolume: '330ml',
    unitsPerPackage: 30,
    size: '330ml x 30',
    isSubscriptionAvailable: true,
    sodiumLevel: 10,
    phLevel: 7.0,
    rating: 4.3,
    reviews: 890,
  },
  {
    id: '7',
    nameAr: 'مياه نستله',
    nameEn: 'Nestle Pure Life',
    price: 18.00,
    imageUrl: 'https://picsum.photos/200/300?random=7',
    brand: 'Nestle',
    brandId: 'nestle',
    packagingType: 'CRT',
    unitVolume: '1.5L',
    unitsPerPackage: 12,
    size: '1.5L x 12',
    isSubscriptionAvailable: true,
    sodiumLevel: 14,
    phLevel: 7.3,
    rating: 4.4,
    reviews: 720,
  },
  {
    id: '8',
    nameAr: 'مياه ايفال',
    nameEn: 'Ival Water',
    price: 22.50,
    imageUrl: 'https://picsum.photos/200/300?random=8',
    brand: 'Ival',
    brandId: 'ival',
    packagingType: 'CRT',
    unitVolume: '200ml',
    unitsPerPackage: 48,
    size: '200ml x 48',
    isSubscriptionAvailable: true,
    sodiumLevel: 2,
    phLevel: 7.8,
    rating: 4.6,
    reviews: 410,
  },
  {
    id: '9',
    nameAr: 'مياه العين',
    nameEn: 'Al Ain Water',
    price: 14.50,
    imageUrl: 'https://picsum.photos/200/300?random=9',
    brand: 'Al Ain',
    brandId: 'alain',
    packagingType: 'CRT',
    unitVolume: '330ml',
    unitsPerPackage: 40,
    size: '330ml x 40',
    isSubscriptionAvailable: false,
    sodiumLevel: 8,
    phLevel: 7.1,
    rating: 4.1,
    reviews: 300,
  },
  {
    id: '10',
    nameAr: 'مياه فيحاء',
    nameEn: 'Fayha Water',
    price: 13.00,
    imageUrl: 'https://picsum.photos/200/300?random=10',
    brand: 'Fayha',
    brandId: 'fayha',
    packagingType: 'CRT',
    unitVolume: '330ml',
    unitsPerPackage: 40,
    size: '330ml x 40',
    isSubscriptionAvailable: true,
    sodiumLevel: 25,
    phLevel: 7.2,
    rating: 4.0,
    reviews: 150,
  },
];

export const DONATION_PRODUCTS: Product[] = [
    {
      id: 'don_1',
      nameAr: 'سقيا مساجد (صغير)',
      nameEn: 'Mosque Donation Small',
      price: 15.00,
      imageUrl: 'https://picsum.photos/200/300?random=11',
      brand: 'Store DB Charity',
      brandId: 'charity',
      packagingType: 'CRT',
      unitVolume: '200ml',
      unitsPerPackage: 24,
      size: '24 عبوة x 200مل',
      isSubscriptionAvailable: true,
      sodiumLevel: 0,
      phLevel: 7,
      rating: 5,
      reviews: 999,
      isDonation: true,
    },
    {
      id: 'don_2',
      nameAr: 'سقيا مساجد (كبير)',
      nameEn: 'Mosque Donation Large',
      price: 120.00,
      imageUrl: 'https://picsum.photos/200/300?random=12',
      brand: 'Store DB Charity',
      brandId: 'charity',
      packagingType: 'CRT',
      unitVolume: '330ml',
      unitsPerPackage: 400,
      size: '10 كراتين',
      isSubscriptionAvailable: true,
      sodiumLevel: 0,
      phLevel: 7,
      rating: 5,
      reviews: 999,
      isDonation: true,
    },
];

export const MOCK_BRANDS: BrandInfo[] = [
  {
    id: 'nova',
    nameAr: 'نوفا',
    nameEn: 'Nova',
    logoUrl: 'https://cdn.salla.sa/AEdwj/890c20da-085a-464a-932d-20e363539958-500x500.png',
    description: 'مياه نوفا هي مياه طبيعية ونقية، تُستخرج من أفضل المصادر الجوفية في المملكة العربية السعودية.',
    composition: { ph: 7.4, sodium: 17, calcium: 10, magnesium: 2, potassium: 1, bicarbonate: 100 }
  },
  {
    id: 'berain',
    nameAr: 'بيرين',
    nameEn: 'Berain',
    logoUrl: 'https://cdn.salla.sa/AEdwj/a9030623-f222-4467-8549-d37533604313-500x500.png',
    description: 'مياه بيرين توفر لك الجودة والطعم المثالي، معبأة بتقنيات حديثة لضمان النقاء.',
    composition: { ph: 7.2, sodium: 12, calcium: 15, magnesium: 5, potassium: 3, bicarbonate: 80 }
  },
  {
    id: 'tania',
    nameAr: 'تانيا',
    nameEn: 'Tania',
    logoUrl: 'https://picsum.photos/200/300?random=3',
    description: 'مياه تانيا تأتيكم من قلب الطبيعة، غنية بالمعادن الأساسية لجسم صحي.',
    composition: { ph: 7.0, sodium: 20, calcium: 12, magnesium: 3, potassium: 1, bicarbonate: 90 }
  },
  {
    id: 'zamzam',
    nameAr: 'زمزم',
    nameEn: 'Zamzam',
    logoUrl: 'https://picsum.photos/200/300?random=4',
    description: 'ماء زمزم المبارك، خير ماء على وجه الأرض.',
    composition: { ph: 8.0, sodium: 40, calcium: 40, magnesium: 10, potassium: 5, bicarbonate: 150 }
  },
  {
    id: 'arwa',
    nameAr: 'أروى',
    nameEn: 'Arwa',
    logoUrl: 'https://picsum.photos/200/300?random=5',
    description: 'مياه أروى تتميز بنسبة صوديوم منخفضة، مثالية لنمط حياة صحي ومتوازن.',
    composition: { ph: 6.9, sodium: 3, calcium: 5, magnesium: 1, potassium: 0.5, bicarbonate: 40 }
  },
  {
    id: 'aquafina',
    nameAr: 'أكوافينا',
    nameEn: 'Aquafina',
    logoUrl: 'https://picsum.photos/200/300?random=6',
    description: 'مياه أكوافينا المنقاة بدقة، تضمن لك الطعم النقي والمنعش في كل رشفة.',
    composition: { ph: 7.0, sodium: 10, calcium: 2, magnesium: 1, potassium: 0, bicarbonate: 10 }
  },
  {
    id: 'nestle',
    nameAr: 'نستله',
    nameEn: 'Nestle',
    logoUrl: 'https://picsum.photos/200/300?random=7',
    description: 'نستله بيور لايف، مياه عالية الجودة مناسبة لكل أفراد العائلة.',
    composition: { ph: 7.3, sodium: 14, calcium: 18, magnesium: 4, potassium: 2, bicarbonate: 85 }
  },
  {
    id: 'ival',
    nameAr: 'ايفال',
    nameEn: 'Ival',
    logoUrl: 'https://picsum.photos/200/300?random=8',
    description: 'مياه ايفال النقية، اختيارك الأمثل للترطيب اليومي.',
    composition: { ph: 7.8, sodium: 2, calcium: 8, magnesium: 2, potassium: 1, bicarbonate: 30 }
  },
   {
    id: 'alain',
    nameAr: 'العين',
    nameEn: 'Al Ain',
    logoUrl: 'https://picsum.photos/200/300?random=9',
    description: 'مياه العين، توازن مثالي من المعادن الأساسية.',
    composition: { ph: 7.1, sodium: 8, calcium: 10, magnesium: 3, potassium: 1, bicarbonate: 50 }
  },
   {
    id: 'fayha',
    nameAr: 'فيحاء',
    nameEn: 'Fayha',
    logoUrl: 'https://picsum.photos/200/300?random=10',
    description: 'مياه الفيحاء، نقاء الطبيعة في زجاجة.',
    composition: { ph: 7.2, sodium: 25, calcium: 20, magnesium: 6, potassium: 2, bicarbonate: 110 }
  }
];

export const TIME_SLOTS: TimeSlot[] = [
  { id: 'morning', label: 'صباحاً', range: '09:00 - 13:00' },
  { id: 'afternoon', label: 'ظهراً', range: '13:00 - 18:00' },
  { id: 'evening', label: 'مساءً', range: '18:00 - 22:00' },
];

export const VAT_RATE = 0.15;
export const DELIVERY_FEE = 15.00;
